# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-09 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('emailId', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
