# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-11 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ajUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 11, 11, 35, 47, 57005, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ajuser',
            name='location',
            field=models.CharField(default=datetime.datetime(2017, 8, 11, 11, 36, 0, 881019, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ajuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 8, 11, 11, 36, 7, 233936, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
